name: ignore-paths testing

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '!src/main/resources/application-[dev|docker].yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
      - name: println
        run: |
          echo "hello"
      
